apiVersion: v1
kind: Service
metadata:
  name: image-greyscale-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9191
      targetPort: 80
      protocol: TCP
  selector:
    app: image-greyscale
